name: Build LineageOS 23 (Android 16) for Merlinx

on:
  workflow_dispatch: # Кнопка ручного запуска в панели Actions

env:
  DEVICE: merlinx
  ROM_URL: https://github.com/LineageOS/android.git
  ROM_BRANCH: lineage-23.0
  LOCAL_MANIFEST_URL: https://raw.githubusercontent.com/EmreDemirn-Repos/manifest/main/manifest.xml

jobs:
  build_rom:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maximize Disk Space (Супер-агрессивная очистка)
        run: |
          echo "=== Место ДО очистки ==="
          df -h
          
          # Выносим гигантские папки с кэшем инструментов Гитхаба и тяжелым софтом
          sudo rm -rf /opt/hostedtoolcache \
                      /usr/local/lib/android \
                      /usr/share/dotnet \
                      /opt/ghc \
                      /usr/share/swift \
                      /usr/local/share/boost \
                      /usr/local/lib/node_modules \
                      /etc/mysql \
                      /var/lib/mysql \
                      /usr/share/azure-cli \
                      /opt/az
          
          # Жестко удаляем тяжелые предустановленные пакеты и браузеры
          sudo apt-get purge -y azure-cli google-cloud-sdk microsoft-edge-dev powershell mono-devel mono-runtime-common google-chrome-stable firefox
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          echo "=== Место ПОСЛЕ супер-очистки ==="
          df -h

      - name: Install Build Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3-pip openjdk-17-jdk repo
          git config --global user.name "LineXin"
          git config --global user.email "beka2023bak@gmail.com"

      - name: Sync ROM Source (Синхронизация исходников)
        run: |
          mkdir -p ~/android
          cd ~/android
          
          # Тюнингуем Git, чтобы он не захлебывался на тяжелых бинарниках Клэнга
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          
          # Добавляем --clone-filter=blob:none (дикая экономия места и защита от вылетов)
          repo init --depth=1 --no-repo-verify -u ${{ env.ROM_URL }} -b ${{ env.ROM_BRANCH }} --clone-filter=blob:none
          
          mkdir -p .repo/local_manifests
          curl -sL ${{ env.LOCAL_MANIFEST_URL }} -o .repo/local_manifests/manifest.xml
          
          # Запускаем чистую синхронизацию
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
          
          echo "=== Проверяем остаток места на диске перед компиляцией ==="
          df -h

      - name: Run Compilation (Сборка прошивки)
        run: |
          cd ~/android
          source build/envsetup.sh
          breakfast ${{ env.DEVICE }} userdebug
          mka lineage -j$(nproc --all)
